config/routes.rb
Rails.application.routes.draw do
    resources :todo_lists do
        resources :todo_items do
            member do
                patch :complete
                patch :uncomplete
            end
        end
    end

    authenticated :user do
        root to: 'todo_lists#index', as: :authenticated_root
    end

    root to: redirect('/users/sign_in')

    devise_for :users, controllers: {
        :sessions => "users/sessions",
        :registrations => "users/registrations"
    }

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
    belongs_to :todo_list

    def completed?
        !completed_at.blank?
    end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
    has_many :todo_items
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_todo_list
    before_action :set_todo_item, except: [:create]

    def create
        @todo_item = @todo_list.todo_items.create(todo_item_params)
        redirect_to @todo_list
    end

    def destroy
        @todo_item = @todo_list.todo_items.find(params[:id])
        if @todo_item.destroy
            flash[:success] = "Todo List item was deleted."
        else
            flash[:error] = "Todo List item could not be deleted."
        end
        redirect_to @todo_list
    end

    def complete
        @todo_item.update_attribute(:completed_at, Time.now)
        redirect_to @todo_list, notice: "Todo item completed"
    end

    def uncomplete
        @todo_item.update_attribute(:completed_at, nil)
        redirect_to @todo_list, notice: "Todo item completed state reversed"
    end

    private

    def set_todo_list
        @todo_list = TodoList.find(params[:todo_list_id])
    end

    def set_todo_item
        @todo_item = @todo_list.todo_items.find(params[:id])
    end

    def todo_item_params
        params[:todo_item].permit(:content)
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_todo_list, only: [:show, :edit, :update, :destroy]
    before_action :set_user
    layout 'todos_pages'

    # GET /todo_lists
    # GET /todo_lists.json
    def index
        @todo_lists = TodoList.all.where(user_id: current_user[:id]).order(created_at: :asc)
    end

    # GET /todo_lists/1
    # GET /todo_lists/1.json
    def show
    end

    # GET /todo_lists/new
    def new
        @todo_list = TodoList.new
    end

    # GET /todo_lists/1/edit
    def edit
    end

    # POST /todo_lists
    # POST /todo_lists.json
    def create
        #@todo_list = @user.todo_list.create(todo_list_params)
        #
        puts "todos params", todo_list_params
        @todo_list = TodoList.new(todo_list_params)
        @todo_list.user_id = current_user[:id]

        respond_to do |format|
            if @todo_list.save
                format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
                format.json { render :show, status: :created, location: @todo_list }
            else
                format.html { render :new }
                format.json { render json: @todo_list.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /todo_lists/1
    # PATCH/PUT /todo_lists/1.json
    def update
        respond_to do |format|
            if @todo_list.update(todo_list_params)
                format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
                format.json { render :show, status: :ok, location: @todo_list }
            else
                format.html { render :edit }
                format.json { render json: @todo_list.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /todo_lists/1
    # DELETE /todo_lists/1.json
    def destroy
        @todo_list.destroy
        respond_to do |format|
            format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private

    def set_user
        @user = User.find(current_user[:id])
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
        @todo_list = TodoList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_list_params
        params.require(:todo_list).permit(:title, :description, :user)
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  layout 'user_auth_pages'
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout 'user_auth_pages'
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/delete_me_devise/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/delete_me_devise/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>TodosRuby</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

        <script defer src="https://use.fontawesome.com/releases/v5.14.0/js/all.js"></script>
    </head>

    <body>
        <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>op
            <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        <%#= yield %>
        <%= yield(:todos_pages) or yield %>
        <%= yield(:user_auth) or yield %>
    </body>
</html>

app/views/layouts/todos_pages.html.erb
<% content_for :todos_pages do -%>

    <%= render 'navbar' %>

    <div class="container">
        <div class="box">
            <%= yield %>
        </div>
    </div>
<% end -%>

<%= render :file => 'layouts/application' %>

app/views/layouts/user_auth_pages.html.erb
<% content_for :user_auth do -%>
    <section class="hero is-link is-fullheight">
        <div class="hero-body">
            <div class="container">
                <div class="auth-form-wrap">
                    <%= yield %>
                </div>
            </div>
        </div>
    </section>
<% end -%>

<%= render :file => 'layouts/application' %>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
    <div class="columns is-mobile new-todo">
        <div class="column is-8">
            <%= f.text_field :content, placeholder: "New Todo", :class => 'input' %>
        </div>
        <div class="column is-2">
            <%= f.submit 'Create Todo Item', :class => 'button is-link' %>
        </div>
    </div>
<% end %>

app/views/todo_items/_todo_item.html.erb
<tr>
    <% if todo_item.completed? %>
        <td>
            <%= link_to uncomplete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
                <i class="fa fa-check"></i>
            <% end %>
        </td>
        <td><p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p></td>
        <td>
            <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
                <i class="fa fa-trash"></i>
            <% end %>
        </td>
    <% else %>
        <td>
            <%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
                <i class="far fa-circle"></i>
            <% end %>
        </td>
        <td><p><%= todo_item.content %></p></td>
        <td>
            <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
                <i class="fa fa-trash"></i>
            <% end %>
        </td>
    <% end %>
</tr>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list, local: true) do |form| %>
    <% if todo_list.errors.any? %>
        <div id="error_explanation">
            <h2 class="title is-5"><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from
                being
                saved:</h2>

            <ul>
                <% todo_list.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= form.label :title, :class => 'label' %>
        <%= form.text_field :title, :class => 'input' %>
    </div>

    <div class="field">
        <%= form.label :description, :class => 'label' %>
        <%= form.text_area :description, :class => 'textarea' %>
    </div>

    <div class="actions">
        <%= form.submit 'Create Todo List', :class => 'button is-link' %>
    </div>
<% end %>

app/views/todo_lists/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="https://bulma.io">
            <h3 class="title is-5" style="color: #000!important;">Todos</h3>
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item" href="/todo_lists/">
                Home
            </a>
        </div>

        <div class="navbar-end">
            <% if user_signed_in? %>
                <div class="navbar-item">
                    <b><%= current_user.email %></b>
                </div>
            <% end %>
            <div class="navbar-item">
                <div class="buttons">
                    <% if user_signed_in? %>
                        <%= link_to 'Log Out', destroy_user_session_path, method: :delete, :class => 'button is-light' %>
                    <% else %>
                        <a class="button is-primary">
                            <strong>Sign up</strong>
                        </a>
                        <a class="button is-light">
                            Log in
                        </a>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</nav>

app/views/todo_lists/edit.html.erb
<h1 class="title is-3">Editing Todo List</h1>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title is-3">Todo Lists</h1>

<table class="table">
    <thead>
    <tr>
        <th>Title</th>
        <th>Description</th>
        <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @todo_lists.each do |todo_list| %>
        <tr>
            <td><%= todo_list.title %></td>
            <td><%= todo_list.description %></td>
            <td><%= link_to 'Show', todo_list %></td>
            <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
            <td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Todo List', new_todo_list_path, { :class => 'button is-link' } %>

app/views/todo_lists/new.html.erb
<h1 class="title is-3">New Todo List</h1>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <strong>Title:</strong>
    <%= @todo_list.title %>
</p>

<p>
    <strong>Description:</strong>
    <%= @todo_list.description %>
</p>

<div id="todo_items_wrapper">
    <table class="table is-bordered">
        <tbody>
        <%= render @todo_list.todo_items %>
        </tbody>
    </table>
    <div id="form">
        <%= render "todo_items/form" %>
    </div>
</div>

<hr/>

<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
    <div id="error_explanation">
        <h2>
            <%= I18n.t("errors.messages.not_saved",
                       count: resource.errors.count,
                       resource: resource.class.model_name.human.downcase)
            %>
        </h2>
        <ul>
            <% resource.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
    <%= link_to "Log in", new_session_path(resource_name) %><br/>
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "Sign up", new_registration_path(resource_name) %><br/>
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "Forgot your password?", new_password_path(resource_name) %><br/>
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br/>
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br/>
<% end %>

<%- if devise_mapping.omniauthable? %>
    <%- resource_class.omniauth_providers.each do |provider| %>
        <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %>
        <br/>
    <% end %>
<% end %>